<?php
/**
 * unit-selftest:/form.php
 *
 * @creation  2017-12-10
 * @version   1.0
 * @package   unit-selftest
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 */
namespace OP;

/* @var $app   UNIT\App  */
/* @var $form  UNIT\Form */
/* @var $build string    */

//	...
$keys = [
	'prod'     =>'Product',
	'host'     =>'Host',
	'port'     =>'Port',
	'user'     =>'User',
	'password' =>'Password',
	'charset'  =>'Charset',
];

//	...
$form = Unit('Selftest')->Form();

?>
<section id="UNIT_SELFTEST">
	<?php $form->Start() ?>
		<div role="table">
			<?php foreach($keys as $key => $label ): ?>
			<div class="tr">
				<div>
					<?= $label ?>
				</div>
				<div>
					<?php $form->Input($key) ?>
				</div>
				<div>
					<?php $form->Error($key) ?>
				</div>
			</div>
			<?php endforeach; ?>
			<? if( \OP\UNIT\SELFTEST\Inspector::Failed() ): ?>
			<div>
				<div>

				</div>
				<div>
					<label>
					<input type="checkbox" name="build" value="<?= $build ?? null ?>" />Build
					</label>
				</div>
			</div>
			<? endif; ?>
			<div>
				<div>
				</div>
				<div>
					<button> Submit </button>
				</div>
			</div>
		</div>
	<?php $form->Finish() ?>
</section>
<?php
//	...
//$form->Debug();
