<?php
/**
 * unit-selftest:/form.php
 *
 * @creation  2017-12-10
 * @version   1.0
 * @package   unit-selftest
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<div>
	<div>
		<div>
			User
		</div>
		<div>
			<input type="text" value="" />
		</div>
	</div>
	<div>
		<div>
			Password
		</div>
		<div>
			<input type="password" value="" />
		</div>
	</div>
	<div>
		<div>
			Charset
		</div>
		<div>
			<input type="text" value="" />
		</div>
	</div>
	<div>
		<div>
		</div>
		<div>
			<button> Submit </button>
		</div>
	</div>
</div>